
resolver: lts-6.1
compiler: ghc-7.10.3

# fails: see https://github.com/commercialhaskell/stack/issues/563
# resolver: lts-2.22
# compiler: ghc-7.8.4
# the mimimum version tested by travis

packages:
- '.'

extra-deps: []
